### ISSUE TITLE
H2 database empty

### ISSUE THREAD

**Issue by andrewmagill** [ESIPFed/Geoweaver#55]
H2 database seems to be empty after Linux quick install.

Database files are moved to ~/ by install script.  Can connect only using the default H2 credentials:

username: sa
password: [blank]

(username: geoweaver, password: geoweaver does not work)

After connecting, no tables exist.

I am new to Java, H2, etc., so this may be user error.

Thank you.

**Comment by ZihengSun** [comment]
Have you tried to open the h2 files in the db folder? Are there tables?

On 1/31/2020 12:52 PM, Andrew Magill wrote:

H2 database seems to be empty after Linux quick install.

Database files are moved to ~/ by install script. Can connect only using the default H2 credentials:

username: sa
password: [blank]

(username: geoweaver, password: geoweaver does not work)

After connecting, no tables exist.

I am new to Java, H2, etc., so this may be user error.

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1dSol237qifD69qpFBXkEX09eyhgy5dFoGRNZFQY0MpFi6jSI7cv7C3wKRBgF0PfyX2anvomi-aetE79cP6iNrNkSmnobs14rvWVI7CF2LOTdqeUR6My13FJdf7nd0-rZ_PMyts0DlHn476SyTM9cjMjwwAOtCcbtYRoQHxM_ZAnm1koalfqWadpjvPP7Enn9K69SRLAmzMtSljhLZno-9Z6ibhqcL1nFNbndecTbIwcpnmou_f2li65keE95BUeTCyat1m_sizEHO4jxbZx7ZQmZ8I1V67hi0bpy5qSZcTTF8Y4Gpr0VW1JRedEvey3ncuFQle6wPmosoice3bX58LYIHeEd9_eCw5xkx-PgqRSvV-CCsGeFhCQzPM0A8hkIpXfG0kDAH3eUfsY4h6eQQD1k10XieidjseHZmF7M69_Jr2F71qfW0X74SwwVXxBd/https%3A%2F%2Fgithub.com%2FESIPFed%2FGeoweaver%2Fissues%2F55%3Femail_source%3Dnotifications%26email_token%3DAEEFH276FFXCL2LZHZW7SGTRARQNHA5CNFSM4KOK3YVKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IKGT2BA>, or unsubscribe<https://secure-web.cisco.com/1G763soR-6z3gj6O9FrYWslIZkL_Ft7nRKPYaoMeJ_Z3!
2oGLVtTA7alEgh-VhdfoSxT1gu6h7bsgpfdE9qIaMcbZJK5UpfPEj0RC9eMx3Zj_Qrrk2GsIt4GxpnE8psA01BSizBo9ZN-neqidXb4ZpmKgVxEo-zCeMFekQkqoQ1jLZNydo2eC3drxcZtO_pjVAogDGccIRZzwqquHBn86jPn0HEBBqUnwTGRuTh_ku8h598nNS-Fp7g0_4-luRXFPKLuC_R3eneghUDEqdpP7gFZUsdErMnHW0kcM2uUPn6ybtq5SfqZq3if9RLaa5h2esL-TaaltuF_vnYMpI11mzFlMf_B5jVN_VZSWmiHhGe752IN23Rip_caLTjNWfzBw5OP4SjsZsTrCUSsTQ5CyaBbTMlU8xfERA2tFSmXREBid-E5uFF3k6ff9fARfj6rac/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEEFH26QT6YRUW7UXYT2ZSDRARQNHANCNFSM4KOK3YVA>.

--
Ziheng Sun, Ph.D.
Research Assistant Professor
Center for Spatial Information Science and Systems
George Mason University
E-mail:zsun@gmu.edu<mailto:E-mail:zsun@gmu.edu>
Tel: 1-703-993-6124
Website:http://zihengsun.github.io
Mailing address: 4400 University Drive, MSN 6E1, Fairfax, VA 22030

**Comment by andrewmagill** [comment]
I did, and I expected I would be able to open it, but I think perhaps the problem is that there are multiple databases in that directory.

However, I think maybe I see the problem.  The install script copies database files to the user's home directory, but the config file does not reference them there, instead the connection is listed as:

database_url=jdbc:h2:~/geoweaver

Also note that git create a Geoweaver directory (not geoweaver), so I think this may be the issue.

**Comment by andrewmagill** [comment]
OK, we can close this issue.  The database is working and I can connect.  I thought there was a problem with Geoweaver because after adding a host I did not see it in a Hosts list on the right side of the screen. However, it shows up after I maximize the screen.  I will create a separate gh issue for UI fix.

**Comment by ZihengSun** [comment]
I will create another issue on the hidden panel and close this one.
